In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s4e12/sample_submission.csv
/kaggle/input/playground-series-s4e12/train.csv
/kaggle/input/playground-series-s4e12/test.csv

In [2]:
train_data = pd.read_csv('/kaggle/input/playground-series-s4e12/train.csv')
test_data = pd.read_csv('/kaggle/input/playground-series-s4e12/test.csv')
submission = pd.read_csv('/kaggle/input/playground-series-s4e12/sample_submission.csv')

In [3]:
train_data.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,...,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
0,0,19.0,Female,10049.0,Married,1.0,Bachelor's,Self-Employed,22.598761,Urban,...,2.0,17.0,372.0,5.0,2023-12-23 15:21:39.134960,Poor,No,Weekly,House,2869.0
1,1,39.0,Female,31678.0,Divorced,3.0,Master's,NaN,15.569731,Rural,...,1.0,12.0,694.0,2.0,2023-06-12 15:21:39.111551,Average,Yes,Monthly,House,1483.0
2,2,23.0,Male,25602.0,Divorced,3.0,High School,Self-Employed,47.177549,Suburban,...,1.0,14.0,NaN,3.0,2023-09-30 15:21:39.221386,Good,Yes,Weekly,House,567.0
3,3,21.0,Male,141855.0,Married,2.0,Bachelor's,NaN,10.938144,Rural,...,1.0,0.0,367.0,1.0,2024-06-12 15:21:39.226954,Poor,Yes,Daily,Apartment,765.0
4,4,21.0,Male,39651.0,Single,1.0,Bachelor's,Self-Employed,20.376094,Rural,...,0.0,8.0,598.0,4.0,2021-12-01 15:21:39.252145,Poor,Yes,Weekly,House,2022.0

In [4]:
test_data.head()

,id,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Policy Start Date,Customer Feedback,Smoking Status,Exercise Frequency,Property Type
0,1200000,28.0,Female,2310.0,NaN,4.0,Bachelor's,Self-Employed,7.657981,Rural,Basic,NaN,19.0,NaN,1.0,2023-06-04 15:21:39.245086,Poor,Yes,Weekly,House
1,1200001,31.0,Female,126031.0,Married,2.0,Master's,Self-Employed,13.381379,Suburban,Premium,NaN,14.0,372.0,8.0,2024-04-22 15:21:39.224915,Good,Yes,Rarely,Apartment
2,1200002,47.0,Female,17092.0,Divorced,0.0,PhD,Unemployed,24.354527,Urban,Comprehensive,NaN,16.0,819.0,9.0,2023-04-05 15:21:39.134960,Average,Yes,Monthly,Condo
3,1200003,28.0,Female,30424.0,Divorced,3.0,PhD,Self-Employed,5.136225,Suburban,Comprehensive,1.0,3.0,770.0,5.0,2023-10-25 15:21:39.134960,Poor,Yes,Daily,House
4,1200004,24.0,Male,10863.0,Divorced,2.0,High School,Unemployed,11.844155,Suburban,Premium,NaN,14.0,755.0,7.0,2021-11-26 15:21:39.259788,Average,No,Weekly,House

* Train data for training, testing (80%,20%)
* Test data has to be submitted

In [5]:
train_data.columns

Index(['id', 'Age', 'Gender', 'Annual Income', 'Marital Status',
       'Number of Dependents', 'Education Level', 'Occupation', 'Health Score',
       'Location', 'Policy Type', 'Previous Claims', 'Vehicle Age',
       'Credit Score', 'Insurance Duration', 'Policy Start Date',
       'Customer Feedback', 'Smoking Status', 'Exercise Frequency',
       'Property Type', 'Premium Amount'],
      dtype='object')

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1200000 non-null  int64
 1   Age                   1181295 non-null  float64
 2   Gender                1200000 non-null  object
 3   Annual Income         1155051 non-null  float64
 4   Marital Status        1181471 non-null  object
 5   Number of Dependents  1090328 non-null  float64
 6   Education Level       1200000 non-null  object
 7   Occupation            841925 non-null   object
 8   Health Score          1125924 non-null  float64
 9   Location              1200000 non-null  object
 10  Policy Type           1200000 non-null  object
 11  Previous Claims       835971 non-null   float64
 12  Vehicle Age           1199994 non-null  float64
 13  Credit Score          1062118 non-null  float64
 14  Insurance Duration    1199999 non-null  float64
 15  Policy Start Date     1200000 non-null  object
 16  Customer Feedback     1122176 non-null  object
 17  Smoking Status        1200000 non-null  object
 18  Exercise Frequency    1200000 non-null  object
 19  Property Type         1200000 non-null  object
 20  Premium Amount        1200000 non-null  float64
dtypes: float64(9), int64(1), object(11)
memory usage: 192.3+ MB

In [7]:
train_data.describe()

,id,Age,Annual Income,Number of Dependents,Health Score,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Premium Amount
count,1.200000e+06,1.181295e+06,1.155051e+06,1.090328e+06,1.125924e+06,835971.000000,1.199994e+06,1.062118e+06,1.199999e+06,1.200000e+06
mean,5.999995e+05,4.114556e+01,3.274522e+04,2.009934e+00,2.561391e+01,1.002689,9.569889e+00,5.929244e+02,5.018219e+00,1.102545e+03
std,3.464103e+05,1.353995e+01,3.217951e+04,1.417338e+00,1.220346e+01,0.982840,5.776189e+00,1.499819e+02,2.594331e+00,8.649989e+02
min,0.000000e+00,1.800000e+01,1.000000e+00,0.000000e+00,2.012237e+00,0.000000,0.000000e+00,3.000000e+02,1.000000e+00,2.000000e+01
25%,2.999998e+05,3.000000e+01,8.001000e+03,1.000000e+00,1.591896e+01,0.000000,5.000000e+00,4.680000e+02,3.000000e+00,5.140000e+02
50%,5.999995e+05,4.100000e+01,2.391100e+04,2.000000e+00,2.457865e+01,1.000000,1.000000e+01,5.950000e+02,5.000000e+00,8.720000e+02
75%,8.999992e+05,5.300000e+01,4.463400e+04,3.000000e+00,3.452721e+01,2.000000,1.500000e+01,7.210000e+02,7.000000e+00,1.509000e+03
max,1.199999e+06,6.400000e+01,1.499970e+05,4.000000e+00,5.897591e+01,9.000000,1.900000e+01,8.490000e+02,9.000000e+00,4.999000e+03

* Total rows = 1.200000e+06

In [8]:
total_row_count = 1.200000e+06
train_data.isna().sum() / total_row_count

id                      0.000000e+00
Age                     1.558750e-02
Gender                  0.000000e+00
Annual Income           3.745750e-02
Marital Status          1.544083e-02
Number of Dependents    9.139333e-02
Education Level         0.000000e+00
Occupation              2.983958e-01
Health Score            6.173000e-02
Location                0.000000e+00
Policy Type             0.000000e+00
Previous Claims         3.033575e-01
Vehicle Age             5.000000e-06
Credit Score            1.149017e-01
Insurance Duration      8.333333e-07
Policy Start Date       0.000000e+00
Customer Feedback       6.485333e-02
Smoking Status          0.000000e+00
Exercise Frequency      0.000000e+00
Property Type           0.000000e+00
Premium Amount          0.000000e+00
dtype: float64

* Null values are there

# Find Problematic Columns

In [9]:
for column in train_data.columns:
    missing_count = train_data[column].isna().sum()
    if missing_count > 0:
        print(column,"====>",missing_count,"=======",train_data[column].dtype)

Age ====> 18705 ======= float64
Annual Income ====> 44949 ======= float64
Marital Status ====> 18529 ======= object
Number of Dependents ====> 109672 ======= float64
Occupation ====> 358075 ======= object
Health Score ====> 74076 ======= float64
Previous Claims ====> 364029 ======= float64
Vehicle Age ====> 6 ======= float64
Credit Score ====> 137882 ======= float64
Insurance Duration ====> 1 ======= float64
Customer Feedback ====> 77824 ======= object

# Analyze each column seperately

## Int, Float columns

In [10]:
train_data[['Age','Annual Income','Number of Dependents','Health Score','Previous Claims','Vehicle Age','Credit Score','Insurance Duration']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 8 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Age                   1181295 non-null  float64
 1   Annual Income         1155051 non-null  float64
 2   Number of Dependents  1090328 non-null  float64
 3   Health Score          1125924 non-null  float64
 4   Previous Claims       835971 non-null   float64
 5   Vehicle Age           1199994 non-null  float64
 6   Credit Score          1062118 non-null  float64
 7   Insurance Duration    1199999 non-null  float64
dtypes: float64(8)
memory usage: 73.2 MB

In [11]:
train_data[['Age','Annual Income','Number of Dependents','Health Score','Previous Claims','Vehicle Age','Credit Score','Insurance Duration']].describe()

,Age,Annual Income,Number of Dependents,Health Score,Previous Claims,Vehicle Age,Credit Score,Insurance Duration
count,1.181295e+06,1.155051e+06,1.090328e+06,1.125924e+06,835971.000000,1.199994e+06,1.062118e+06,1.199999e+06
mean,4.114556e+01,3.274522e+04,2.009934e+00,2.561391e+01,1.002689,9.569889e+00,5.929244e+02,5.018219e+00
std,1.353995e+01,3.217951e+04,1.417338e+00,1.220346e+01,0.982840,5.776189e+00,1.499819e+02,2.594331e+00
min,1.800000e+01,1.000000e+00,0.000000e+00,2.012237e+00,0.000000,0.000000e+00,3.000000e+02,1.000000e+00
25%,3.000000e+01,8.001000e+03,1.000000e+00,1.591896e+01,0.000000,5.000000e+00,4.680000e+02,3.000000e+00
50%,4.100000e+01,2.391100e+04,2.000000e+00,2.457865e+01,1.000000,1.000000e+01,5.950000e+02,5.000000e+00
75%,5.300000e+01,4.463400e+04,3.000000e+00,3.452721e+01,2.000000,1.500000e+01,7.210000e+02,7.000000e+00
max,6.400000e+01,1.499970e+05,4.000000e+00,5.897591e+01,9.000000,1.900000e+01,8.490000e+02,9.000000e+00

## Martial Status

In [12]:
train_data['Marital Status'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1200000 entries, 0 to 1199999
Series name: Marital Status
Non-Null Count    Dtype
--------------    -----
1181471 non-null  object
dtypes: object(1)
memory usage: 9.2+ MB

In [13]:
train_data['Marital Status'].unique()

array(['Married', 'Divorced', 'Single', nan], dtype=object)

## Occupation

In [14]:
train_data['Occupation'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1200000 entries, 0 to 1199999
Series name: Occupation
Non-Null Count   Dtype
--------------   -----
841925 non-null  object
dtypes: object(1)
memory usage: 9.2+ MB

In [15]:
train_data['Occupation'].unique()

array(['Self-Employed', nan, 'Employed', 'Unemployed'], dtype=object)

## Customer Feedback column

In [16]:
train_data['Customer Feedback'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1200000 entries, 0 to 1199999
Series name: Customer Feedback
Non-Null Count    Dtype
--------------    -----
1122176 non-null  object
dtypes: object(1)
memory usage: 9.2+ MB

In [17]:
train_data['Customer Feedback'].unique()

array(['Poor', 'Average', 'Good', nan], dtype=object)

* What we can do to address this null values

1. Remove null values (Current decision)
2. Regenerate values

# Remove null values

In [18]:
train_data_dropna = train_data.dropna()
print("Removal percentage :",round((train_data.shape[0]-train_data_dropna.shape[0])/train_data.shape[0]*100,3),"%")

Removal percentage : 68.0 %

* Removing is not the best option

# Generating values for null

## Model based Imputation for Numerical data

In [21]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=8)
numerical_columns = ['Age','Annual Income','Number of Dependents','Health Score','Previous Claims','Vehicle Age','Credit Score','Insurance Duration']
train_data[numerical_columns] = imputer.fit_transform(train_data[numerical_columns])

KeyboardInterrupt:

## Label Encoding + KNN Imputation for Categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder

categorical_columns = ['Marital Status', 'Occupation']
encoder = LabelEncoder()

for column in categorical_columns:
    train_data[column] = encoder.fit_transform(train_data[column].astype(str))

imputer = KNNImputer(n_neighbors=5)
train_data[categorical_columns] = imputer.fit_transform(train_data[categorical_columns])

# Revert encoding if necessary
for column in categorical_columns:
    train_data[column] = encoder.inverse_transform(train_data[column].astype(int))

In [ ]:
train_data.isna().sum()